import fs from 'node:fs/promises';import {chromium} from '/tmp/before-dawn-tools/node_modules/playwright/index.mjs';
const b=await chromium.launch({headless:true,args:['--no-sandbox']});const p=await b.newPage({viewport:{width:1440,height:900}});const report={errors:[],screens:[],inputs:[]};p.on('pageerror',e=>report.errors.push(e.message));
await p.goto('http://127.0.0.1:3187',{waitUntil:'networkidle'});
for(const [id,next] of [['titleScreen','titleStart'],['modeScreen','mode'],['fighterScreen','fighterNext'],['stageScreen','startButton']]){report.screens.push(await p.locator('#'+id).evaluate(e=>({id:e.id,rect:e.getBoundingClientRect().toJSON(),viewport:[innerWidth,innerHeight],overflow:[document.documentElement.scrollWidth,document.documentElement.scrollHeight]})));await p.locator(id==='modeScreen'?'.mode-option.active':'#'+next).click();}
await p.waitForFunction(()=>window.__fight?.fighters.length===2);await p.waitForTimeout(2800);
await p.evaluate(()=>window.__fight.debugForce({phase:'fight',cpu:false,fighters:[{x:400,y:590,health:100,action:null,stun:0},{x:650,y:590,health:100,action:null,stun:0}]}));
await p.keyboard.down('w');await p.waitForTimeout(40);await p.keyboard.up('w');await p.keyboard.down('k');await p.waitForTimeout(150);await p.keyboard.up('k');report.inputs.push(await p.evaluate(()=>window.__fight.snapshot()));await p.locator('#gameCanvas').screenshot({path:'artifacts/critic-live-airKick.png'});
await p.keyboard.press('Escape');await p.locator('#matchOverlay').screenshot({path:'artifacts/critic-live-pause.png'});report.screens.push({pauseVisible:await p.locator('#matchOverlay').isVisible()});await p.keyboard.press('Escape');
await fs.writeFile('artifacts/critic-nav.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await b.close();
