import assert from 'node:assert/strict';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import {setTimeout as delay} from 'node:timers/promises';
import {Client} from '@colyseus/sdk';
import {matchMaker} from '@colyseus/core';
process.env.NODE_ENV='test';process.env.PORT='3195';process.env.RANKING_DB=path.join(await mkdtemp(path.join(tmpdir(),'buteco-online-')),'ranking.sqlite');
const {gameServer,rankings}=await import('../server.mjs');
const endpoint='http://127.0.0.1:3195';
const profile=async data=>(await fetch(endpoint+'/api/profile',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})).json();
const a=await profile({name:'Host'}),b=await profile({guest:true}),c=await profile({guest:true});assert.match(b.name,/Desafiante/);
const client=new Client(endpoint),rooms=[];
const track=room=>{rooms.push(room);room.events=[];room.onMessage('*',(type,data)=>{room.events.push({type,data});if(type==='probe')room.send('pong',data);});room.send('sync');return room;};
const until=async condition=>{for(let n=0;n<120;n++){if(await condition())return;await delay(30);}throw Error('Timed out');};
try {
  const host=track(await client.create('fight',{token:a.token}));const guest=track(await client.joinById(host.roomId,{token:b.token}));
  const room=matchMaker.getLocalRoomById(host.roomId);await until(()=>room.members.size===2);
  await assert.rejects(client.joinById(host.roomId,{token:c.token}));
  guest.send('kick');guest.send('configure',{stage:3,fighter:'miranda'});guest.send('start');await delay(60);assert.equal(room.stage,0);assert.equal(room.phase,'waiting');assert.equal([...room.members.values()][1].fighter,'bruno');
  host.send('kick');await until(()=>room.members.size===1);assert.equal(rankings.list().length,0);await assert.rejects(client.joinById(host.roomId,{token:b.token}));
  const challenger=track(await client.joinById(host.roomId,{token:c.token}));
  room.probePlayers();await until(()=>[...room.members.values()].every(p=>Number.isInteger(p.ping)));const ping=[...room.members.values()][0].ping;host.send('pong',{nonce:'invalid',ping:9999});await delay(30);assert.equal([...room.members.values()][0].ping,ping);
  const select=async()=>{
    host.send('start');await until(()=>room.phase==='fighters');
    const previousFighter=[...room.members.values()][1].fighter;
    challenger.send('configure',{fighter:'constructor',stage:3});host.send('configure',{fighter:'__proto__'});await delay(30);assert.equal(room.stage,0);assert.equal([...room.members.values()][1].fighter,previousFighter);
    challenger.send('configure',{fighter:'miranda'});await until(()=>[...room.members.values()][1].fighter==='miranda');
    host.send('ready');await delay(30);assert.equal(room.phase,'fighters');challenger.send('ready');await until(()=>room.phase==='stage');
    challenger.send('configure',{stage:3});challenger.send('start');await delay(30);assert.equal(room.phase,'stage');assert.equal(room.stage,0);
    host.send('configure',{stage:2});await until(()=>room.stage===2);host.send('start');await until(()=>room.phase==='loading');
    host.send('loaded',{matchId:'old-match'});await delay(30);assert.equal([...room.members.values()][0].loaded,false);
    host.send('loaded',{matchId:room.matchId});challenger.send('loaded',{matchId:room.matchId});await until(()=>room.phase==='fighting');
  };
  await select();
  const viewerProfile=await profile({guest:true});
  const viewer=track(await client.joinById(host.roomId,{token:viewerProfile.token,spectator:true}));
  await until(()=>room.spectators.size===1);
  await until(()=>viewer.events.some(e=>e.type==='prepare')&&viewer.events.some(e=>e.type==='frame'));
  assert.equal(room.members.size,2);
  const listed=await (await fetch(endpoint+'/api/rooms')).json();assert.ok(listed.some(r=>r.id===host.roomId&&r.phase==='fighting'));
  viewer.send('cancelSelection');viewer.send('ready');viewer.send('configure',{fighter:'maya',stage:3});viewer.send('input',['left']);await delay(60);assert.equal(room.phase,'fighting');
  await viewer.leave();await until(()=>room.spectators.size===0);assert.equal(room.phase,'fighting');assert.equal(rankings.list().length,0);
  const spectator=track(await client.joinById(host.roomId,{token:viewerProfile.token,spectator:true}));
  await until(()=>room.spectators.size===1);
  const extraViewers=[];
  for(let i=0;i<9;i++){const p=await profile({guest:true});extraViewers.push(track(await client.joinById(host.roomId,{token:p.token,spectator:true})));}
  await until(()=>room.spectators.size===10);
  const overflow=await profile({guest:true});await assert.rejects(client.joinById(host.roomId,{token:overflow.token,spectator:true}));
  assert.ok((await (await fetch(endpoint+'/api/rooms')).json()).some(r=>r.id===host.roomId&&r.spectators===10));
  for(const v of extraViewers)await v.leave();await until(()=>room.spectators.size===1);
  room.simulation.phase='fight';const x=room.simulation.fighters[1].x;challenger.send('input',['left']);await delay(100);assert.ok(room.simulation.fighters[1].x<x);challenger.send('input',[]);
  host.send('result',{winner:1});host.send('input',['invalid']);await delay(40);assert.equal(rankings.list().length,0);
  const win=async damaged=>{const g=room.simulation;if(damaged){g.fighters[0].health=80;await until(()=>room.damaged[0]);}for(let n=0;n<2;n++){g.fighters[1].health=0;g.finishRound();g.phaseTime=.001;await until(()=>n===0?g.round===2:room.phase==='waiting');}};
  const originalId=room.roomId;await win(false);assert.equal(rankings.list()[0].perfects,1);assert.equal(room.roomId,originalId);assert.equal(room.members.size,2);assert.equal(room.simulation,null);assert.equal(room.spectators.size,1);await until(()=>spectator.events.some(e=>e.type==='lobby'&&e.data.phase==='waiting'));
  room.stage=0;await select();await win(true);assert.equal(rankings.list()[0].wins,2);assert.equal(rankings.list()[0].perfects,1);
  room.stage=0;await select();await challenger.leave();await until(()=>rankings.list()[0].wins===3);assert.equal(rankings.list()[0].perfects,1);
  host.send('start');await delay(30);assert.equal(room.phase,'waiting');await host.leave();await until(()=>!matchMaker.getLocalRoomById(originalId));
  assert.equal((await fetch(endpoint+'/data/ranking.sqlite')).status,403);
  console.log('PASS host-only start/stage, independent live fighter choices, confirmation, same-room auto return, ping nonce/RTT, guest identity, authoritative scores, perfects and forfeit');
}finally{for(const room of rooms)try{if(room.connection.isOpen)await Promise.race([room.leave(),delay(200)]);}catch{}await gameServer.gracefullyShutdown(false);rankings.close();}
