const SOURCE='/assets/audio/sources/round-announcer.mp3';
const KEY='buteco-voice-picker-v1';
const PHRASES=[['round-1','Primeiro round'],['round-2','Segundo round'],['round-3','Terceiro round'],['final-round','Round final'],['fight','Lutem!'],['ko','K.O.'],['winner','Vitória'],['other','Outra frase']];
const $=selector=>document.querySelector(selector);
let context,buffer,clips=[],playing=null;
const status=text=>$('#status').textContent=text;
function stop(){if(playing){playing.onended=null;playing.stop();playing.disconnect();playing=null;}document.querySelectorAll('.playing').forEach(el=>el.classList.remove('playing'));}
async function play(clip,element){stop();$('#original').pause();await context.resume();const source=context.createBufferSource();source.buffer=buffer;source.connect(context.destination);source.start(0,clip.start,clip.end-clip.start);playing=source;element?.classList.add('playing');source.onended=()=>{if(playing===source){playing=null;element?.classList.remove('playing');}source.disconnect();};}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({source:SOURCE,clips}));$('#saved').textContent='Escolhas e cortes salvos neste navegador.';}catch{$('#saved').textContent='Exporte o JSON para guardar suas escolhas.';}}
function valid(rows){return Array.isArray(rows)&&rows.length>0&&rows.length<=500&&rows.every(c=>Number.isFinite(c.start)&&Number.isFinite(c.end)&&c.start>=0&&c.end<=buffer.duration+.001&&c.end>c.start&&typeof c.phrase==='string'&&(!c.phrase||PHRASES.some(([id])=>id===c.phrase))&&(!c.name||typeof c.name==='string'))&&new Set(rows.filter(c=>c.phrase&&c.phrase!=='other').map(c=>c.phrase)).size===rows.filter(c=>c.phrase&&c.phrase!=='other').length;}
function detect(){
 stop();const gap=Number($('#gap').value),threshold=Number($('#threshold').value);
 if(!Number.isFinite(gap)||gap<.15||gap>3||!Number.isFinite(threshold)||threshold< -65||threshold> -15){status('Use silêncio de 0,15 a 3 segundos e sensibilidade de -65 a -15 dB.');return;}
 const rate=buffer.sampleRate,step=Math.round(rate*.01),channels=Array.from({length:buffer.numberOfChannels},(_,i)=>buffer.getChannelData(i)),frames=[];
 for(let offset=0;offset<buffer.length;offset+=step){let energy=0,n=0;for(const data of channels)for(let j=offset;j<Math.min(offset+step,data.length);j++){energy+=data[j]*data[j];n++;}frames.push(Math.sqrt(energy/n)>Math.pow(10,threshold/20));}
 const spans=[];let start=null,last=0;
 for(let i=0;i<frames.length;i++){if(frames[i]){if(start===null)start=i*.01;last=(i+1)*.01;}else if(start!==null&&i*.01-last>=gap){if(last-start>=.2)spans.push({start:Math.max(0,start-.08),end:Math.min(buffer.duration,last+.12),phrase:'',name:''});start=null;}}
 if(start!==null&&last-start>=.2)spans.push({start:Math.max(0,start-.08),end:Math.min(buffer.duration,last+.12),phrase:'',name:''});
 clips=spans;persist();render();status(`${clips.length} sugestões de cortes. Ouça e identifique as frases; a separação não faz transcrição.`);
}
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function wav(clip){const first=Math.floor(clip.start*buffer.sampleRate),last=Math.min(buffer.length,Math.ceil(clip.end*buffer.sampleRate)),channels=buffer.numberOfChannels,size=(last-first)*channels*2,bytes=new ArrayBuffer(44+size),view=new DataView(bytes);const text=(at,str)=>{for(let i=0;i<str.length;i++)view.setUint8(at+i,str.charCodeAt(i));};text(0,'RIFF');view.setUint32(4,36+size,true);text(8,'WAVE');text(12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*channels*2,true);view.setUint16(32,channels*2,true);view.setUint16(34,16,true);text(36,'data');view.setUint32(40,size,true);let offset=44;for(let i=first;i<last;i++)for(let c=0;c<channels;c++){const sample=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));view.setInt16(offset,sample<0?sample*32768:sample*32767,true);offset+=2;}return new Blob([bytes],{type:'audio/wav'});}
function waveform(canvas,clip){const g=canvas.getContext('2d');canvas.width=900;canvas.height=72;const data=buffer.getChannelData(0),first=Math.floor(clip.start*buffer.sampleRate),last=Math.ceil(clip.end*buffer.sampleRate),step=Math.max(1,Math.floor((last-first)/900));g.strokeStyle=clip.phrase?'#ffcd4b':'#ad90ef';g.beginPath();for(let x=0;x<900;x++){let peak=0;for(let i=first+x*step;i<Math.min(last,first+(x+1)*step);i++)peak=Math.max(peak,Math.abs(data[i]||0));g.moveTo(x,36-peak*34);g.lineTo(x,36+peak*34);}g.stroke();}
function render(){
 stop();$('#clips').replaceChildren();$('#chosen').replaceChildren();$('#count').textContent=`(${clips.length})`;$('#export').disabled=!clips.some(c=>c.phrase);
 clips.forEach((clip,index)=>{
 const card=document.createElement('article');card.className=`clip${clip.phrase?' selected':''}`;card.innerHTML=`<div class="clip-head"><h3>Tentativa ${index+1}</h3><label>Usar para<select aria-label="Frase da tentativa ${index+1}"><option value="">Não selecionada</option>${PHRASES.map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select></label></div><canvas aria-label="Forma de onda"></canvas><div class="bounds"><label>Início (s)<input class="start" type="number" min="0" step="0.01"></label><label>Fim (s)<input class="end" type="number" min="0" step="0.01"></label><label>Nome / anotação<input class="name" type="text" maxlength="100" placeholder="Opcional"></label><div class="buttons"><button class="play">▶ Ouvir</button><button class="stop">Parar</button><button class="download">Baixar WAV</button><button class="join">Juntar com próximo</button><button class="remove danger">Excluir corte</button></div></div>`;
 const select=card.querySelector('select');select.value=clip.phrase;select.onchange=()=>{clip.phrase=select.value;if(clip.phrase&&clip.phrase!=='other')for(const other of clips)if(other!==clip&&other.phrase===clip.phrase)other.phrase='';persist();render();};
 for(const boundary of ['start','end']){const input=card.querySelector(`.${boundary}`);input.value=clip[boundary].toFixed(2);input.max=buffer.duration.toFixed(3);input.onchange=()=>{const value=Number(input.value);if(input.value===''||!Number.isFinite(value)||value<0||value>buffer.duration||(boundary==='start'?value>=clip.end:value<=clip.start)){input.value=clip[boundary].toFixed(2);status('O início precisa estar antes do fim, dentro da gravação.');return;}stop();clip[boundary]=value;persist();waveform(card.querySelector('canvas'),clip);};}
 const name=card.querySelector('.name');name.value=clip.name||'';name.oninput=()=>{clip.name=name.value;persist();};
 card.querySelector('.play').onclick=()=>play(clip,card);card.querySelector('.stop').onclick=stop;card.querySelector('.download').onclick=()=>download(wav(clip),`${clip.phrase||'tentativa'}-${index+1}.wav`);
 card.querySelector('.join').disabled=index===clips.length-1;card.querySelector('.join').onclick=()=>{const next=clips[index+1];if(next.phrase&&!clip.phrase)clip.phrase=next.phrase;clip.start=Math.min(clip.start,next.start);clip.end=Math.max(clip.end,next.end);clips.splice(index+1,1);persist();render();};
 card.querySelector('.remove').onclick=()=>{clips.splice(index,1);persist();render();};$('#clips').append(card);waveform(card.querySelector('canvas'),clip);
 if(clip.phrase){const choice=document.createElement('div');choice.className='choice';const title=document.createElement('p');title.textContent=`${PHRASES.find(([id])=>id===clip.phrase)[1]} · tentativa ${index+1}`;choice.append(title);const listen=document.createElement('button');listen.textContent='▶ Ouvir escolha';listen.onclick=()=>play(clip,card);const save=document.createElement('button');save.textContent='Baixar WAV';save.onclick=card.querySelector('.download').onclick;choice.append(listen,save);$('#chosen').append(choice);}
 });if(!clips.some(c=>c.phrase))$('#chosen').textContent='Marque uma tentativa na opção “Usar para”.';
}
$('#detect').onclick=()=>{if(clips.some(c=>c.phrase)&&!confirm('Refazer os cortes apaga as escolhas atuais. Continuar?'))return;detect();};
$('#add').onclick=()=>{clips.push({start:0,end:Math.min(2,buffer.duration),phrase:'',name:''});persist();render();$('#clips').lastElementChild?.scrollIntoView({behavior:'smooth'});};
$('#original').onplay=stop;
$('#export').onclick=()=>download(new Blob([JSON.stringify({version:1,source:SOURCE,duration:buffer.duration,clips,selected:clips.filter(c=>c.phrase)},null,2)],{type:'application/json'}),'vozes-escolhidas.json');
$('#import').onchange=async event=>{try{const data=JSON.parse(await event.target.files[0].text());if(data.source!==SOURCE||!valid(data.clips))throw Error('invalid');clips=data.clips;persist();render();status('Escolhas importadas.');}catch{status('Arquivo inválido ou cortes fora da gravação.');}event.target.value='';};
try{context=new AudioContext();const response=await fetch(SOURCE);if(!response.ok)throw Error('missing');buffer=await context.decodeAudioData(await response.arrayBuffer());let saved;try{saved=JSON.parse(localStorage.getItem(KEY));}catch{}if(saved?.source===SOURCE&&valid(saved.clips)){clips=saved.clips;render();status('Cortes e escolhas anteriores restaurados.');}else detect();$('#detect').disabled=false;$('#add').disabled=false;}catch(error){$('#status').classList.add('error');status('Não foi possível carregar a gravação. Abra esta página pelo servidor do jogo.');console.error(error);}
